### ISSUE TITLE
Need a good demo project

### ISSUE THREAD

**Issue by ppwfx** [yuriizinets/ssceng#22]
Hey guys,

looks pretty cool. Is there a demo of an app running on it anywhere? Plus, what's SSC?

Best

**Comment by yuriizinets** [comment]
Hey!
For now, you can check `web` folder. Website landing itself uses SSC for components separation. But, to be honest, it's not so good example in terms of using all available features. I had old `demo` project, which was a bit outdated and not entirely clear. I'm working on providing better documentation and demo now.
SSC - Server Side Components, is a way to use components approach with old-fashioned templates. It ships with set of features, like asynchronous operations, methods, etc.
Main idea - use server side as much as possible, with minimal JS payload.

For now, main consumer of a library is BrokerOne team: https://mybrokerone.com.
Most of the fronend was done using this library.

So, I'll leave this issue as a requirement for good demo project :)

**Comment by ppwfx** [comment]
mybrokerone.one is a great example. would be great to see how it's implemented in the backend, but I can wait :)

great potential, and very ambitious, really looking forward to seeing where this is going!

**Comment by yuriizinets** [comment]
Unfortunately, I can't share BrokerOne project parts. I'll talk with my team, maybe I'll release a few articles with interesting usage examples. Instead, I've provided basic demo project with using of components approach and some library features. It can be found here: https://github.com/yuriizinets/ssceng/tree/master/demo
Also, I've improved Quick Start section in documentation, so it would be easier to start.

Closing this issue for now. If you need more detailed demo, please, re-open this issue with details, or contact me directly. I understand that not all features are covered by demo page. I'll improve it during writing documentation.
